### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MatheushVinha** [matt-harrell/dnd-encounter-creator#27]
dude, i have a question, why do you use react to make this site, why is it better or is it your favorite language?

**Comment by Matt-Langdon08** [comment]
Hey MatheushVinha,

I used React because it is the current JavaScript library I am learning but this could be done on another library/framework like Angular or Vue. 

All these JavaScript libraries/Frameworks handle state([article here to explain state in the context of React](https://www.simplilearn.com/tutorials/reactjs-tutorial/reactjs-state)) which helps with this app since the UI is constantly changing with the user's input.

**Comment by MatheushVinha** [comment]
interesting to know, thank you very much
